spring:
  datasource:
    driverClassName: org.h2.Driver
    password: imdb
    url: jdbc:h2:mem:imdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect



server:
  servlet:
    context-path: /imdb